### PR TITLE
Fix bytesToHex()

### LINKED ISSUE #354: Binary tab in QR Scan Mode is broken
https://github.com/GrapheneOS/Camera/blob/71462d8762f7f8c0217be4f09fe22bab6c7bf8a3/app/src/main/java/app/grapheneos/camera/ui/activities/MainActivity.kt#L1060-L1071

The output string uses at least 3 characters per byte of input, so the output length shouldn't be `bytes.size`.
Furthermore, the loop shouldn't be skipping over input bytes with `step 3` nor excluding the last byte.

I might submit a PR to fix this if I get the time.

### PR DESCRIPTION
**Pull request by delitako**
Fixes #354

### CODE REVIEW

File: app/src/main/java/app/grapheneos/camera/ui/activities/MainActivity.kt [hunk 1]
```diff
@@ -1058,16 +1058,35 @@ open class MainActivity : AppCompatActivity(),
...
+        // Add a newline every 8 bytes (unless end)
+
+        var outLen = bytes.size * 3 // 2 hex digits + 1 space/newline per byte
+        outLen += bytes.size / 4 // Double spaces
+        outLen -= bytes.size / 8 // No double space when newline
+        outLen -= 1 // No trailing space/newline
+        if (bytes.size % 4 == 0 && bytes.size % 8 != 0)
+            outLen -= 1 // No trailing double space
+
+        val hexChars = CharArray(outLen)
```
Comment (octocorvus) [inline app/src/main/java/app/grapheneos/camera/ui/activities/MainActivity.kt:1072]: for an empty `ByteArray`, `outLen` will be `-1`, which will cause exception when `CharArray` is initialised (might crash the app, if not handled). early returning an empty string (if the size of `ByteArray` is zero) can mitigate this

File: app/src/main/java/app/grapheneos/camera/ui/activities/MainActivity.kt [hunk 2]
```diff
@@ -1058,16 +1058,35 @@ open class MainActivity : AppCompatActivity(),
...
+        // Add a space between every byte
+        // Double space every 4 bytes (unless end or newline)
+        // Add a newline every 8 bytes (unless end)
+
+        var outLen = bytes.size * 3 // 2 hex digits + 1 space/newline per byte
+        outLen += bytes.size / 4 // Double spaces
+        outLen -= bytes.size / 8 // No double space when newline
+        outLen -= 1 // No trailing space/newline
+        if (bytes.size % 4 == 0 && bytes.size % 8 != 0)
+            outLen -= 1 // No trailing double space
```
Comment (octocorvus) [inline app/src/main/java/app/grapheneos/camera/ui/activities/MainActivity.kt:1070]: this can be simplified to:
```kt
var outLen = bytes.size * 3 - 1 // 2 hex digits + 1 space/newline per byte (except last)
outLen += bytes.size / 8 // One double space per row except the last incomplete row
if (bytes.size % 8 > 4) {
    outLen += 1 // One double space for the last incomplete row, if it has >4 columns
}
```
also, note the usage of braces for `if` statement, read [android style guide](https://developer.android.com/kotlin/style-guide#braces) for more info

File: app/src/main/java/app/grapheneos/camera/ui/activities/MainActivity.kt [hunk 3]
```diff
@@ -1058,16 +1058,35 @@ open class MainActivity : AppCompatActivity(),
...
     open fun bytesToHex(bytes: ByteArray): String {
-        val hexChars = CharArray(bytes.size)
-        for (i in 0 until bytes.indices.last - 1 step 3) {
-            val v: Int = bytes[i].toInt() and 0xFF
-            hexChars[i] = hexArray[v ushr 4]
-            hexChars[i + 1] = hexArray[v and 0x0F]
-            hexChars[i + 2] = ' '
+        // Add a space between every byte
+        // Double space every 4 bytes (unless end or newline)
+        // Add a newline every 8 bytes (unless end)
```
Comment (octocorvus) [inline app/src/main/java/app/grapheneos/camera/ui/activities/MainActivity.kt:1063]: (optional): it might be better to make it clear that the output is formatted as a matrix

**Review by octocorvus — CHANGES_REQUESTED** [review]

File: app/src/main/java/app/grapheneos/camera/ui/activities/MainActivity.kt [hunk 4]
```diff
@@ -1058,16 +1058,38 @@ open class MainActivity : AppCompatActivity(),
...
+
+        var outLen = bytes.size * 3 - 1 // 2 hex digits + 1 space/newline per byte (except last)
+        outLen += bytes.size / 8 // One double space per row except the last incomplete row
+        if (bytes.size % 8 > 4) {
+            outLen += 1 // One double space for the last incomplete row, if it has >4 columns
         }
+
+        // outLen will be wrong for empty inputs
+        if (bytes.isEmpty()) return ""
```
Comment (octocorvus) [inline app/src/main/java/app/grapheneos/camera/ui/activities/MainActivity.kt:1073]: Can you move this higher? Ideally, it should return before `outLen` is calculated, since it doesn't make much sense to calculate `outLen` if `bytes` is empty.

**Review by octocorvus — CHANGES_REQUESTED** [review]

File: app/src/main/java/app/grapheneos/camera/ui/activities/MainActivity.kt (hunk 4 above)
Comment (delitako) [reply app/src/main/java/app/grapheneos/camera/ui/activities/MainActivity.kt:1073]: Yeah I thought the code flowed better this way even though calculating `outLen` first is useless. I'll change it though.

**Review by octocorvus — APPROVED** [review]
looks good to me
